<?php
/**
 * Génère un mapping complet jeux => catégories
 */

$games_categories = [
    'ARC Raiders' => 1, // Action
    'ARK: Survival Ascended' => 15, // Survival
    "Assassin's Creed Odyssey" => 2, // Aventure
    'Call of Duty: Black Ops II' => 3, // Shooter
    'Call of Duty 4: Modern Warfare' => 3, // Shooter
    'DayZ' => 15, // Survival
    'Fortnite' => 3, // Shooter
    'Genshin Impact' => 13, // RPG
    'Grand Theft Auto VI' => 2, // Aventure
    'League of Legends' => 4, // Stratégie
    'Minecraft' => 14, // Sandbox
    'Call of Duty: Modern Warfare 2' => 3, // Shooter
    'Rocket League' => 7, // Sport
    'Warframe' => 3, // Shooter
    'Wuthering Waves' => 13, // RPG
    "Tom Clancy's Rainbow Six Siege" => 3, // Shooter
    'Sekiro: Shadows Die Twice' => 1, // Action
    'Control' => 1, // Action
    'Subnautica' => 15, // Survival
    'Cities: Skylines' => 5, // Simulation
    'Factorio' => 5, // Simulation
    'Hades' => 13, // RPG
    'Dead Cells' => 16, // Fighting
    'Cuphead' => 10, // Plateforme
    'Stardew Valley' => 5, // Simulation
    'Terraria' => 14, // Sandbox
    'Among Us' => 12, // Indie
    'Phasmophobia' => 8, // Horreur
    'Outlast' => 8, // Horreur
    'The Forest' => 15, // Survival
    'Valheim' => 15, // Survival
    "No Man's Sky" => 2, // Aventure
    'Forza Horizon 5' => 6, // Course
    'FIFA 23' => 7, // Sport
    'NBA 2K24' => 7, // Sport
    'Tekken 8' => 16, // Fighting
    'Street Fighter 6' => 16, // Fighting
    'Monster Hunter: World' => 1, // Action
    'Darkest Dungeon' => 13, // RPG
    'RimWorld' => 5, // Simulation
    'Planet Zoo' => 5, // Simulation
    'Satisfactory' => 5, // Simulation
    'Age of Empires IV' => 4, // Stratégie
    'Total War: Warhammer III' => 4, // Stratégie
    'StarCraft II' => 4, // Stratégie
    'Diablo IV' => 13, // RPG
    'Path of Exile' => 13, // RPG
    'Fall Guys' => 7, // Sport
    'Slay the Spire' => 4, // Stratégie
    'Celeste' => 10, // Plateforme
    'Inside' => 10, // Plateforme
    'Limbo' => 10, // Plateforme
    'Rust' => 15, // Survival
    'Ark: Survival Evolved' => 15, // Survival
    'Sea of Thieves' => 2, // Aventure
    'Guild Wars 2' => 11, // MMO
    'Black Desert Online' => 11, // MMO
    'The Crew Motorfest' => 6, // Course
    'Gran Turismo 7' => 6, // Course
    'Mortal Kombat 1' => 16, // Fighting
    'It Takes Two' => 2, // Aventure
    'Little Nightmares II' => 8, // Horreur
    'Undertale' => 13, // RPG
    'Vampire Survivors' => 12, // Indie
    'Project Zomboid' => 15, // Survival
    'Mount & Blade II: Bannerlord' => 4, // Stratégie
    'Hogwarts Legacy' => 2, // Aventure
    'The Legend of Zelda: Tears of the Kingdom' => 2, // Aventure
    'Starfield' => 13, // RPG
    'Elden Ring' => 1, // Action
    'Spider-Man 2 (PS5)' => 1, // Action
    'Horizon Forbidden West: Burning Shores' => 2, // Aventure
    'Resident Evil 4 Remake' => 8, // Horreur
    'Final Fantasy XVI' => 13, // RPG
    "Assassin's Creed Mirage" => 2, // Aventure
    'God of War Ragnarök' => 1, // Action
    'Apex Legends' => 3, // Shooter
    'Valorant' => 3, // Shooter
    'Call of Duty: Modern Warfare II (2022)' => 3, // Shooter
    'Overwatch 2' => 3, // Shooter
    'Destiny 2' => 3, // Shooter
    'GTA Online' => 2, // Aventure
    'Hollow Knight: Silksong' => 10, // Plateforme
    'Loop Hero' => 17, // Roguelike
    'Tunic' => 2, // Aventure
    'Sifu' => 1, // Action
    'Stray' => 2, // Aventure
    'Oxenfree II: Lost Signals' => 2, // Aventure
    'Rainbow Six Extraction' => 3, // Shooter
    'Brawlhalla' => 16, // Fighting
    'Paladins' => 3, // Shooter
    'The Callisto Protocol' => 8, // Horreur
    'Alan Wake 2' => 8, // Horreur
    'Redfall' => 3, // Shooter
    'Avowed' => 13, // RPG
    'Fable (Reboot)' => 13, // RPG
];

echo "-- Mapping de catégories pour tous les jeux\n\n";
foreach ($games_categories as $game => $cat_id) {
    echo "'$game' => $cat_id,\n";
}
?>
